CREATE DATABASE IF NOT EXISTS  hive_DB;

DROP TABLE IF EXISTS hive_DB.DISTINCT_FACILITIES;

CREATE EXTERNAL TABLE IF NOT EXISTS hive_DB.DISTINCT_FACILITIES (
FACILITY_NAME   varchar(255) 
)
COMMENT 'DISTINCT FACILITY_NAME in datatset'
ROW FORMAT DELIMITED
   FIELDS TERMINATED BY '|'
LOCATION 'dist_facility_nm';

###


DROP TABLE IF EXISTS hive_DB.ADMISSIONS_PERCENT;

CREATE EXTERNAL TABLE IF NOT EXISTS hive_DB.ADMISSIONS_PERCENT (
YEAR INT,
FACILITY_NAME varchar(255),
NOT_ADMITTED INT,
ADMISSIONS INT,
ADMIT_PERCENT DOUBLE
)
COMMENT 'Number of admissions by Facility'
ROW FORMAT DELIMITED
   FIELDS TERMINATED BY '|'
LOCATION 'admit_percent';
